create table if not exists phones
(
    id         bigint generated by default as identity constraint pk_phones primary key,
    person_id bigint not null,
    number       varchar(255) not null,
    created_at timestamp with time zone not null,
    CONSTRAINT fk_person FOREIGN KEY(person_id) REFERENCES persons(id)
);

insert into phones (number, person_id, created_at)
select phone, id, created_at from persons;

alter table persons drop column phone;
