version: '3.1'
services:
  db_regional_programs:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command: ["postgres", "-c", "log_statement=all"]
  adminer:
    image: adminer
    restart: always
    ports:
      - "8333:8080"
