---
datasource:
  default: ${APP_ENV}

  prod:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

  dev:
    username: sa
    password: sa
    url: jdbc:h2:file:./db

ebean:
  ddl:
    run: true
    generate: true
#    seedSql: seed.sql
#  migration:
#    run: true